### ISSUE TITLE
Support Python 3

### ISSUE THREAD

**Issue by altendky** [Julian/mkenv#28]
`*shrug*`  I'd rather not have to use 2 for mkenv...  But perhaps you have some opinions about that?  I presume I'd have to do this myself (starting with `filesystems`).  :]  I suppose that if you would be amenable to this you may still have some preferences on how to do 2/3 support.

**Comment by Julian** [comment]
Yep happy to have this -- actually this was one of the original reasons I *wrote* Filesystems :P, `betterpath` (which is the next best path library I'm aware of) doesn't support Py3 well [there were others FWIW, but yeah].

Same codebase is my preference pretty much. I'm guessing that like Windows, once Filesystems is knocked out, this part would be trivial.
